<?php
/**
 * @package    Joomla.Component.Builder
 *
 * @created    4th September, 2022
 * @author     Llewellyn van der Merwe <https://dev.vdm.io>
 * @git        Joomla Component Builder <https://git.vdm.dev/joomla/Component-Builder>
 * @copyright  Copyright (C) 2015 Vast Development Method. All rights reserved.
 * @license    GNU General Public License version 2 or later; see LICENSE.txt
 */

namespace VDM\Joomla\Componentbuilder\Package\Component\Readme;


use VDM\Joomla\Interfaces\Readme\ItemInterface;


/**
 * Compiler Component Item Readme
 * 
 * @since  5.2.1
 */
final class Item implements ItemInterface
{
	/**
	 * Get an item readme
	 *
	 * @param object  $item  An item details.
	 *
	 * @return string
	 * @since 3.2.2
	 */
	public function get(object $item): string
	{
		// build readme
		$readme = ["```
     ██╗ ██████╗  ██████╗ ███╗   ███╗██╗      █████╗                              
     ██║██╔═══██╗██╔═══██╗████╗ ████║██║     ██╔══██╗                             
     ██║██║   ██║██║   ██║██╔████╔██║██║     ███████║                             
██   ██║██║   ██║██║   ██║██║╚██╔╝██║██║     ██╔══██║                             
╚█████╔╝╚██████╔╝╚██████╔╝██║ ╚═╝ ██║███████╗██║  ██║                             
 ╚════╝  ╚═════╝  ╚═════╝ ╚═╝     ╚═╝╚══════╝╚═╝  ╚═╝                             
                                                                                  
 ██████╗ ██████╗ ███╗   ███╗██████╗  ██████╗ ███╗   ██╗███████╗███╗   ██╗████████╗
██╔════╝██╔═══██╗████╗ ████║██╔══██╗██╔═══██╗████╗  ██║██╔════╝████╗  ██║╚══██╔══╝
██║     ██║   ██║██╔████╔██║██████╔╝██║   ██║██╔██╗ ██║█████╗  ██╔██╗ ██║   ██║   
██║     ██║   ██║██║╚██╔╝██║██╔═══╝ ██║   ██║██║╚██╗██║██╔══╝  ██║╚██╗██║   ██║   
╚██████╗╚██████╔╝██║ ╚═╝ ██║██║     ╚██████╔╝██║ ╚████║███████╗██║ ╚████║   ██║   
 ╚═════╝ ╚═════╝ ╚═╝     ╚═╝╚═╝      ╚═════╝ ╚═╝  ╚═══╝╚══════╝╚═╝  ╚═══╝   ╚═╝   
```"];
		// system name
		$readme[] = "# " . $item->name;

		if (!empty($item->description))
		{
			$readme[] = "\n" . $item->description;
		}
		elseif (!empty($item->short_description))
		{
			$readme[] = "\n" . $item->short_description;
		}

		$readme[] = "\nThe Joomla component generated by JCB is a complete mini‑application bundled into one installable extension: it carries its own manifest, database schema, models, controllers, admin and site views, routing rules, language strings, ACL policies, helper classes, and assets. On installation it creates its tables, registers menus, wires itself to Joomla’s event system, and serves bespoke dashboards and frontend pages that handle every CRUD workflow. By encapsulating every layer—from data storage and validation to presentation and access control—within a single, self‑sufficient package, the component becomes the authoritative hub for its entire feature set inside the Joomla ecosystem. By using the \"reset\" button, you can instantly synchronize this Joomla Component with the authoritative version hosted in our core repository, ensuring your Component always benefit from the latest refinements, performance optimizations, and security enhancements.\n\n Want to simply utilize this Comonent for something more unique and fitting to your requirements? Fork the repo, modify the Component, and point JCB to your branch. Whether you’re wiring advanced admin views, sculpting intricate data relationships, or embedding dynamic dashboards, you stay in charge while still enjoying JCB’s effortless deployment workflow.\n
\n
\"This flexible approach embraces JCB’s open-source model, giving you the freedom to adapt your components to your exact needs while staying connected to a powerful and community-driven ecosystem.\"\n";

		// yes you can remove this, but why?
		$readme[] = "\n---\n```
     ██╗ ██████╗██████╗
     ██║██╔════╝██╔══██╗
     ██║██║     ██████╔╝
██   ██║██║     ██╔══██╗
╚█████╔╝╚██████╗██████╔╝
 ╚════╝  ╚═════╝╚═════╝
```\n> Build with [Joomla Component Builder](https://git.vdm.dev/joomla/Component-Builder)\n\n";

		return implode("\n", $readme);
	}
}

